<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="myPool" tests="1" failures="1" errors="0" time="11.919" skipped="0" timestamp="2018-11-08T11:19:01">
  <testcase name="test1" time="11.919" classname="com.example">
    <failure><![CDATA[Exception in thread "main" java.lang.RuntimeException: A test exception
  at com.example.stacktrace.StackTraceExample.methodB(StackTraceExample.java:13)
  at com.example.stacktrace.StackTraceExample.methodA(StackTraceExample.java:9)
  at com.example.stacktrace.StackTraceExample.main(StackTraceExample.java:5)]]></failure>
  </testcase>
</testsuite>
